version: '3.8'

services:

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - cashier-network

  backend:
    build: ./backend
    ports:
      - "8000:80"
    environment:
      - DB_HOST=mysql
      - DB_NAME=smart_cashier
      - DB_USER=root
      - DB_PASS=password
    volumes:
      - ./backend/src:/var/www/html/src
    depends_on:
      - mysql
    networks:
      - cashier-network

  mysql:
    build: ./database
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: smart_cashier
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - cashier-network

volumes:
  mysql_data:

networks:
  cashier-network:
    driver: bridge